name: Deploy to EC2

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - ".gitignore"
      - ".env.example"
      - "LICENSE"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/screennet

            # Guardar el hash del último commit
            LAST_COMMIT=$(git rev-parse HEAD)

            # Actualizar código
            git pull origin master

            # Si no hay cambios, salir
            if [ "$LAST_COMMIT" = "$(git rev-parse HEAD)" ]; then
              echo "No hay cambios para desplegar"
              exit 0
            fi

            # Instalar solo si hay cambios en package.json
            if git diff --name-only $LAST_COMMIT HEAD | grep -q "package.json"; then
              echo "Cambios detectados en package.json, instalando dependencias..."
              npm ci --production
            fi

            # Construir y reiniciar
            npm run build
            pm2 restart screennet --update-env
